name: tankit-dev

services:
  frontend:
    build:
      context: ./frontend/game
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./frontend/game/src:/app/src
      - ./frontend/game/index.html:/app/index.html
      - ./frontend/game/public:/app/public
      - ./frontend/game/vite:/app/vite
      - ./frontend/game/package.json:/app/package.json
      - ./frontend/game/tsconfig.json:/app/tsconfig.json
      - ./frontend/game/log.js:/app/log.js
    ports:
      !override
      - "${FRONTEND_PORT:-5174}:8080"
