// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TankIt.Api.Data;

#nullable disable

namespace TankIt.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003142121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TankIt.Api.Models.Championship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<short>("PlayerCount")
                        .HasColumnType("smallint")
                        .HasColumnName("player_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<short>("TargetScore")
                        .HasColumnType("smallint")
                        .HasColumnName("target_score");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.HasKey("Id")
                        .HasName("pk_championships");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("idx_championships_created_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_championships_status");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("idx_championships_winner_id");

                    b.ToTable("championships", null, t =>
                        {
                            t.HasCheckConstraint("championships_player_count_check", "player_count BETWEEN 2 AND 4");

                            t.HasCheckConstraint("championships_status_check", "status IN ('pending', 'in_progress', 'completed')");

                            t.HasCheckConstraint("championships_target_score_check", "target_score > 0");
                        });
                });

            modelBuilder.Entity("TankIt.Api.Models.ChampionshipParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChampionshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("championship_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsAi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_ai");

                    b.Property<string>("TankColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tank_color");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_championship_participants");

                    b.HasIndex("ChampionshipId")
                        .HasDatabaseName("idx_championship_participants_championship_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_championship_participants_user_id");

                    b.HasIndex("ChampionshipId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_championship_participants_user_per_championship")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("championship_participants", null, t =>
                        {
                            t.HasCheckConstraint("championship_participants_is_ai_user_id_check", "is_ai = true OR user_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TankIt.Api.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ChampionshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("championship_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<bool>("IsRanked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_ranked");

                    b.Property<int>("MapSeed")
                        .HasColumnType("integer")
                        .HasColumnName("map_seed");

                    b.Property<short>("PlayerCount")
                        .HasColumnType("smallint")
                        .HasColumnName("player_count");

                    b.Property<short?>("SequenceNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence_number");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasDefaultValue("lobby")
                        .HasColumnName("status");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("ChampionshipId")
                        .HasDatabaseName("idx_matches_championship_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_matches_status");

                    b.HasIndex("WinnerId")
                        .HasDatabaseName("idx_matches_winner_id");

                    b.HasIndex("ChampionshipId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_matches_championship_sequence")
                        .HasFilter("championship_id IS NOT NULL");

                    b.ToTable("matches", null, t =>
                        {
                            t.HasCheckConstraint("matches_championship_id_sequence_number_check", "championship_id IS NULL OR sequence_number IS NOT NULL");

                            t.HasCheckConstraint("matches_player_count_check", "player_count BETWEEN 2 AND 4");

                            t.HasCheckConstraint("matches_status_check", "status IN ('lobby', 'in_progress', 'completed', 'aborted')");
                        });
                });

            modelBuilder.Entity("TankIt.Api.Models.MatchParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("EloDelta")
                        .HasColumnType("integer")
                        .HasColumnName("elo_delta");

                    b.Property<int>("Hits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("hits");

                    b.Property<bool>("IsAi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_ai");

                    b.Property<int>("Kills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("kills");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<short?>("Placement")
                        .HasColumnType("smallint")
                        .HasColumnName("placement");

                    b.Property<short?>("Points")
                        .HasColumnType("smallint")
                        .HasColumnName("points");

                    b.Property<int>("ShotsFired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("shots_fired");

                    b.Property<int?>("SurvivedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("survived_seconds");

                    b.Property<string>("TankColor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tank_color");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_match_participants");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("idx_match_participants_match_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_match_participants_user_id");

                    b.HasIndex("MatchId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_match_participants_user_per_match")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("match_participants", null, t =>
                        {
                            t.HasCheckConstraint("match_participants_is_ai_user_id_check", "is_ai = true OR user_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TankIt.Api.Models.OAuthAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_oauth_accounts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_oauth_accounts_user_id");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("oauth_accounts_provider_provider_user_id_key");

                    b.ToTable("oauth_accounts", null, t =>
                        {
                            t.HasCheckConstraint("oauth_accounts_provider_check", "provider IN ('google', 'github', 'fortytwo')");
                        });
                });

            modelBuilder.Entity("TankIt.Api.Models.PlayerStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Deaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("deaths");

                    b.Property<int>("EloRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000)
                        .HasColumnName("elo_rating");

                    b.Property<int>("Kills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("kills");

                    b.Property<int>("MatchesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("matches_played");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("wins");

                    b.HasKey("UserId")
                        .HasName("pk_player_stats");

                    b.HasIndex("EloRating")
                        .HasDatabaseName("idx_player_stats_elo")
                        .HasAnnotation("Npgsql:IndexSortOrder", new[] { SortOrder.Descending });

                    b.ToTable("player_stats", (string)null);
                });

            modelBuilder.Entity("TankIt.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("refresh_tokens_token_hash_key");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TankIt.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users_email_key");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("users_username_key");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TankIt.Api.Models.Championship", b =>
                {
                    b.HasOne("TankIt.Api.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_championships_users_created_by");

                    b.HasOne("TankIt.Api.Models.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_championships_users_winner_id");

                    b.Navigation("Creator");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TankIt.Api.Models.ChampionshipParticipant", b =>
                {
                    b.HasOne("TankIt.Api.Models.Championship", "Championship")
                        .WithMany("Participants")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_championship_participants_championships_championship_id");

                    b.HasOne("TankIt.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_championship_participants_users_user_id");

                    b.Navigation("Championship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TankIt.Api.Models.Match", b =>
                {
                    b.HasOne("TankIt.Api.Models.Championship", "Championship")
                        .WithMany("Matches")
                        .HasForeignKey("ChampionshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_matches_championships_championship_id");

                    b.HasOne("TankIt.Api.Models.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_matches_users_winner_id");

                    b.Navigation("Championship");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TankIt.Api.Models.MatchParticipant", b =>
                {
                    b.HasOne("TankIt.Api.Models.Match", "Match")
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_participants_matches_match_id");

                    b.HasOne("TankIt.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_match_participants_users_user_id");

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TankIt.Api.Models.OAuthAccount", b =>
                {
                    b.HasOne("TankIt.Api.Models.User", "User")
                        .WithMany("OAuthAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oauth_accounts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TankIt.Api.Models.PlayerStats", b =>
                {
                    b.HasOne("TankIt.Api.Models.User", "User")
                        .WithOne("Stats")
                        .HasForeignKey("TankIt.Api.Models.PlayerStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_stats_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TankIt.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("TankIt.Api.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TankIt.Api.Models.Championship", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("TankIt.Api.Models.Match", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("TankIt.Api.Models.User", b =>
                {
                    b.Navigation("OAuthAccounts");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
